# Generated by Django 4.2.20 on 2025-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
