# Generated by Django 4.2.20 on 2025-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_authtoken_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
