# Generated by Django 4.2.20 on 2025-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authtoken_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='profile_image',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
