version: '3.8'

services:
  # PostgreSQL DB replacing Mongo
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin - Web GUI for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Backend service for Django.
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
      DB_HOST: postgres
      DJANGO_SETTINGS_MODULE: backend.settings
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      -  ./backend/logs:/app/backend/logs

  # Frontend service for React.
  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend

  # Redis service for Channels - allows for broadcasting
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:
