version: '3.8'

services:
  # PostgreSQL DB replacing Mongo
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend service for Django.
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
      DB_HOST: postgres
    expose:
      - "8000"
    depends_on:
      - postgres

  # Frontend service for React.
  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend

  # Reverse proxy to route requests to the correct service.
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
