version: '3.8'

services:
  mongo:
    image: mongo:4.2.5
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  # Backend service for Django.
  backend:
    build:
      context: .
      dockerfile: Dockerfile    # This now refers to 312-SuperSeniors/backend/Dockerfile
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: "true"
      MONGO_URI: "mongodb://mongo:27017/backend"
    expose:
      - "8000"
    # We do not map backend's port directly to host if we're using a reverse proxy.
    depends_on:
      - mongo
  
  # Frontend service for React.
  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend

  # Reverse proxy to route requests to the correct service.
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"   # Exposes the reverse proxy on host port 8080.
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
