version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_DB: backend
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: backendpass
      DB_HOST: postgres
      DJANGO_SETTINGS_MODULE: backend.settings
    expose:
      - "8000"
    command: "/wait-for-it.sh postgres:5432 --timeout=30 --strict -- /bin/sh -c 'python manage.py makemigrations lobby core && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 backend.asgi:application'"

    volumes:
      - .:/app
      - ./backend/logs:/app/backend/logs

  frontend:
    build: ./frontend
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:alpine
    ports:    
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:
