# Generated by Django 4.2.20 on 2025-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbystatus',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
