# Generated by Django 4.2.20 on 2025-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_lobbystatus_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbystatus',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
